name: "Botaffiumeiro"
version: "1.0"
slug: "botaffiumeiro"
description: "Modify Telegram links for affiliate links"
arch:
  - amd64
  - aarch64
  - armv7
  - i386
startup: "services"
boot: "auto"
host_network: true
options:
  bot_token: ""
  excluded_users: ""
  log_level: "INFO"
  amazon_affiliate_id: ""
  awin_publisher_id: ""
  awin_advertisers: ""
  admitad_publisher_id: ""
  admitad_advertisers: ""
  aliexpress_discount_codes: ""
schema:
  bot_token: "str"
  excluded_users: "str"
  log_level:
    type: "select"
    options:
      - "DEBUG"
      - "INFO"
      - "WARN"
      - "ERROR"
      - "CRITICAL"
  amazon_affiliate_id: "str"
  awin_publisher_id: "str"
  awin_advertisers: "str"
  admitad_publisher_id: "str"
  admitad_advertisers: "str"
  aliexpress_discount_codes: "str"
